const Recipe = use('App/Models/Recipe');
const Drive = use('Drive');
const { validateAll } = use('Validator');

const debug = require('../../../../preload-safe-debug')(
  'Ferdium:internalServer:RecipeController',
);
const { convertToJSON } = require('../../../../jsUtils');
const path = require('path');
const fs = require('fs');

// Local recipe data paths (generated by `pnpm start:fresh`)
const RECIPES_DIR = path.resolve(__dirname, '../../../../../recipes');
const ALL_JSON_PATH = path.join(RECIPES_DIR, 'all.json');
const FEATURED_JSON_PATH = path.join(RECIPES_DIR, 'featured.json');

let allRecipesCache = null;
let featuredIdsCache = null;

function loadAllRecipes() {
  if (allRecipesCache) return allRecipesCache;
  try {
    if (fs.existsSync(ALL_JSON_PATH)) {
      allRecipesCache = JSON.parse(fs.readFileSync(ALL_JSON_PATH, 'utf-8'));
      return allRecipesCache;
    }
    debug('all.json not found, scanning recipes directory');
    const dirs = fs.readdirSync(RECIPES_DIR, { withFileTypes: true });
    const recipes = [];
    for (const dir of dirs) {
      if (!dir.isDirectory()) continue;
      const pkgPath = path.join(RECIPES_DIR, dir.name, 'package.json');
      if (!fs.existsSync(pkgPath)) continue;
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));
        recipes.push({
          id: pkg.id || dir.name,
          name: pkg.name || dir.name,
          version: pkg.version || '1.0.0',
          icons: pkg.icons || {},
        });
      } catch {}
    }
    allRecipesCache = recipes;
    return allRecipesCache;
  } catch (error) {
    debug('Failed to load recipes:', error.message);
  }
  return [];
}

function loadFeaturedIds() {
  if (featuredIdsCache) return featuredIdsCache;
  try {
    if (fs.existsSync(FEATURED_JSON_PATH)) {
      featuredIdsCache = JSON.parse(fs.readFileSync(FEATURED_JSON_PATH, 'utf-8'));
      return featuredIdsCache;
    }
  } catch (error) {
    debug('Failed to load featured.json:', error.message);
  }
  return [];
}

class RecipeController {
  // List official and custom recipes
  async list({ response }) {
    const officialRecipes = loadAllRecipes();
    const allRecipes = await Recipe.all();
    const customRecipesArray = allRecipes.rows;
    const customRecipes = customRecipesArray.map(recipe => ({
      id: recipe.recipeId,
      name: recipe.name,
      ...convertToJSON(recipe.data),
    }));

    const recipes = [...officialRecipes, ...customRecipes];

    return response.send(recipes);
  }

  // Search official and custom recipes
  async search({ request, response }) {
    // Validate user input
    const validation = await validateAll(request.all(), {
      needle: 'required',
    });
    if (validation.fails()) {
      return response.status(401).send({
        message: 'Please provide a needle',
        messages: validation.messages(),
        status: 401,
      });
    }

    const needle = request.input('needle');

    // Get results
    let results;

    if (needle === 'ferdium:custom') {
      const allRecipes = await Recipe.all();
      const dbResults = allRecipes.toJSON();
      results = dbResults.map(recipe => ({
        id: recipe.recipeId,
        name: recipe.name,
        ...convertToJSON(recipe.data),
      }));
    } else {
      const allRecipes = loadAllRecipes();
      const localOfficial = allRecipes.filter(
        r =>
          r.name?.toLowerCase().includes(needle.toLowerCase()) ||
          r.id?.toLowerCase().includes(needle.toLowerCase()),
      );

      debug('localOfficial:', localOfficial.length);

      const recipeQuery = await Recipe.query()
        .where('name', 'LIKE', `%${needle}%`)
        .fetch();
      const localResultsArray = recipeQuery.toJSON();
      const localCustom = localResultsArray.map(recipe => ({
        id: recipe.recipeId,
        name: recipe.name,
        ...convertToJSON(recipe.data),
      }));

      debug('localCustom:', localCustom.length);

      results = [...localOfficial, ...localCustom];
    }

    return response.send(results);
  }

  // Return an empty array
  update({ response }) {
    return response.send([]);
  }

  async popularRecipes({ response }) {
    const allRecipes = loadAllRecipes();
    const featuredIds = loadFeaturedIds();

    if (featuredIds.length > 0) {
      const featuredRecipes = allRecipes.filter(r =>
        featuredIds.includes(r.id),
      );
      return response.send(featuredRecipes);
    }

    const featuredRecipes = allRecipes.filter(r => r.featured === true);
    return response.send(featuredRecipes);
  }

  async download({ response, params }) {
    const validation = await validateAll(params, {
      recipe: 'required|accepted',
    });
    if (validation.fails()) {
      return response.status(401).send({
        message: 'Please provide a recipe ID',
        messages: validation.messages(),
        status: 401,
      });
    }

    const service = params.recipe;

    if (/\.+/.test(service) || /\/+/.test(service)) {
      return response.send('Invalid recipe name');
    }

    if (await Drive.exists(`${service}.tar.gz`)) {
      return response.send(await Drive.get(`${service}.tar.gz`));
    }

    return response.status(400).send({
      message: 'Recipe not found',
      code: 'recipe-not-found',
    });
  }
}

module.exports = RecipeController;
