; Inno Setup Script for Ferdium
; Generated by build-windows-production.ps1
; Do NOT edit manually - this file is auto-generated during build

#define MyAppName "Ferdium"
#define MyAppVersion "{#AppVersion}"
#define MyAppVersionNumeric "{#AppVersionNumeric}"
#define MyAppPublisher "Ferdium Contributors"
#define MyAppURL "https://ferdium.org/"
#define MyAppExeName "Ferdium.exe"
#define MyAppArch "{#AppArch}"
#define MyAppGitHash "{#AppGitHash}"
#define MyAppBuildNumber "{#AppBuildNumber}"

[Setup]
; App metadata
AppId={{B2F8A3E1-4C5D-4E6F-8A9B-0C1D2E3F4A5B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}

; Installation paths
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
OutputDir=..\out
OutputBaseFilename={#MyAppName}-win-AutoSetup-{#MyAppVersion}-{#MyAppBuildNumber}-{#MyAppArch}

; Compression & performance
Compression=lzma2/ultra64
SolidCompression=yes
LZMAUseSeparateProcess=yes
LZMADictionarySize=65536
DiskSpanning=no

; Installer behavior
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog commandline
DisableProgramGroupPage=yes
WizardStyle=modern
WizardSizePercent=100,100
DisableWelcomePage=no
CloseApplications=yes
RestartApplications=no

; Uninstall
UninstallDisplayIcon={app}\{#MyAppExeName}
UninstallDisplayName={#MyAppName} {#MyAppVersion}

; Version info for the installer itself
VersionInfoVersion={#MyAppVersionNumeric}
VersionInfoCompany={#MyAppPublisher}
VersionInfoDescription={#MyAppName} Installer

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
Name: "french"; MessagesFile: "compiler:Languages\French.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
Name: "japanese"; MessagesFile: "compiler:Languages\Japanese.isl"
Name: "korean"; MessagesFile: "compiler:Languages\Korean.isl"
Name: "spanish"; MessagesFile: "compiler:Languages\Spanish.isl"

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"
Name: "quicklaunchicon"; Description: "Create a &Quick Launch shortcut"; GroupDescription: "Additional icons:"; Flags: unchecked

[Files]
; Main application files
Source: "{#AppSourcePath}*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent unchecked

[Registry]
; Register ferdium:// protocol handler
Root: HKCR; Subkey: "ferdium"; ValueType: "string"; ValueName: ""; ValueData: "URL:Ferdium Protocol"; Flags: uninsdeletekey
Root: HKCR; Subkey: "ferdium"; ValueType: "string"; ValueName: "URL Protocol"; ValueData: ""
Root: HKCR; Subkey: "ferdium\DefaultIcon"; ValueType: "string"; ValueName: ""; ValueData: "{app}\{#MyAppExeName},1"
Root: HKCR; Subkey: "ferdium\shell\open\command"; ValueType: "string"; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

; Register uninstall info
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}"; ValueType: "string"; ValueName: "DisplayName"; ValueData: "{#MyAppName}"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}"; ValueType: "string"; ValueName: "DisplayVersion"; ValueData: "{#MyAppVersion}"
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}"; ValueType: "string"; ValueName: "Publisher"; ValueData: "{#MyAppPublisher}"
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppName}"; ValueType: "string"; ValueName: "DisplayIcon"; ValueData: "{app}\{#MyAppExeName}"

[Code]
{ Check if Inno Setup is running with admin rights }
function InitializeSetup: Boolean;
begin
  Result := True;
end;

{ Custom message for the finished page }
procedure CurPageChanged(CurPageID: Integer);
begin
  if CurPageID = wpFinished then
  begin
    WizardForm.PageDescriptionLabel.Caption := 'Setup completed successfully';
  end;
end;
